
services:
  bot:
    image: ${DOCKER_USERNAME}/tg_warm_bot:main
    container_name: tg-warm-bot
    restart: unless-stopped
    ports:
      - "7231:7231"
    env_file:
      - .env
    volumes:
        - ./sessions:/sessions
