name: Build and Push With Cache   # CI/CD для образов

on:
  push:
    branches: [ main ]              # триггер – пуш в main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # Cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v3         # действия/checkout для git-кода :contentReference[oaicite:7]{index=7}
      - name: Extract Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
            images: ${{ vars.DOCKER_USERNAME }}/tg_warm_bot

      # 2. Login to Registry
      - name: Log in to Docker Hub
        uses: docker/login-action@v3      # docker/login-action :contentReference[oaicite:8]{index=8}
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Build and Push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          cache-from: type=gha,local=/tmp/.buildx-cache
          cache-to: type=gha,mode=max,local=/tmp/.buildx-cache
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/tg_warm_bot:${{ github.ref_name }}